// Turkish motivational quotes collection
const quotes = [
  "Başarı, her gün tekrarlanan küçük çabaların toplamıdır.",
  "Hayallerinin peşinden gitmekten asla vazgeçme.",
  "Her şey imkânsız görünür, ta ki yapılana kadar.",
  "Bugün zor olan, yarın gücün olacak.",
  "Fırtına ne kadar sert eserse, güneş o kadar parlak doğar.",
  "Kendine inan, gerisi gelir.",
  "Düşmek yenilgi değildir, kalkmamak yenilgidir.",
  "En karanlık gece bile bir gün sona erer.",
  "Büyük yolculuklar tek bir adımla başlar.",
  "Cesaretini topla, hayatını değiştir.",
  "Başarısızlık, başarıya giden yolun ta kendisidir.",
  "Zorluklar, seni güçlendirmek için vardır.",
  "Hayat, cesur olanları ödüllendirir.",
  "Hayal et, inan, başar.",
  "Sınırlarını sen belirle, sonra onları aş.",
  "Her yeni gün, yeni bir başlangıçtır.",
  "Güçlü ol, çünkü bu fırtına da geçecek.",
  "Kendi ışığını yak, karanlık kendiliğinden kaybolur.",
  "Yapamam deme, henüz yapamadım de.",
  "Azim, yeteneğin yerini alır.",
  "Bugün ektiğin tohumlar, yarın meyve verecek.",
  "Hayat sana ne verirse versin, ayağa kalk.",
  "Başarı, konfor alanının dışında başlar.",
  "Küçük adımlar, büyük değişimlere yol açar.",
  "Sen düşündüğünden çok daha güçlüsün.",
  "Hedeflerine odaklan, engeller küçülür.",
  "Sabır ve azim, her kapıyı açar.",
  "Kendi hikâyeni sen yaz.",
  "Değişim, cesaretle başlar.",
  "Her zorluk, bir fırsatın habercisidir.",
  "Yıldızlar, sadece karanlıkta parlar.",
  "Hayallerin büyüklüğü, cesaretinin ölçüsüdür.",
  "Bugünün çabası, yarının zaferidir.",
  "İmkânsız, sadece bir bakış açısıdır.",
  "Rüzgâra karşı yürüyen, en güzel manzaraya ulaşır.",
  "Başlamak, bitirmenin yarısıdır.",
  "Kendi yolunu kendin çiz.",
  "Güneş her zaman bulutların arkasındadır.",
  "Dünya, harekete geçenlere aittir.",
  "İnandığın sürece, her şey mümkündür.",
  "Güçlü bir irade, her engeli aşar.",
  "Bugün bir adım at, yarın bir devrim yarat.",
  "Kendinle gurur duyacağın bir hayat yarat.",
  "Zirveye ulaşmak istiyorsan, tırmanmaya başla.",
  "Hayatın anlamı, onu anlamlı kılmaktır.",
  "En iyi zaman şimdi, en iyi yer burasıdır.",
  "Korku geçicidir, pişmanlık kalıcıdır.",
  "Başarı bir yolculuktur, bir varış noktası değil.",
  "Her gün bir mucize için yeni bir şanstır.",
  "Dağları yerinden oynatmak, küçük taşları taşımakla başlar.",
  "Kendini keşfet, sınırlarını yeniden tanımla.",
  "Işığını dünyayla paylaş.",
  "En büyük zafer, kendini yenmektir.",
  "Umut, karanlıktaki en parlak yıldızdır.",
  "Yolculuğun tadını çıkar, hedefe ulaşmak bonus.",
  "Her son, yeni bir başlangıcın kapısıdır.",
  "Potansiyelini keşfetmek için sınırlarını zorla.",
  "Hayat kısa, hayallerin büyük olsun.",
  "Tutku ile yapılan iş, başarıyı getirir.",
  "Bugün verdiğin emek, yarın seni tanımlayacak.",
  "Zorluklar, başarının kapısını açan anahtarlardır.",
  "Gelecek, bugünden hazırlananlara aittir.",
  "Hayal edebildiğin her şey gerçektir.",
  "Kimseden daha iyi olmaya çalışma, dünkü kendinden daha iyi olmaya çalış.",
  "Başarı, hazırlıkla fırsatın karşılaştığı yerdir.",
  "Engeller, sadece hedefine giden yoldaki basamaklardır.",
  "Asla pes etme, çünkü tam o sırada mucizeler gerçekleşebilir.",
  "Küçük başlangıçlar, büyük sonlara gebedir.",
  "Bir şeye gerçekten inanırsan, dünya senin için döner.",
  "Zamanını boşa harcama, o senin en değerli hazinendir.",
  "Her gün bir adım at, sonunda zirveye ulaşırsın.",
  "Başkalarının ne düşündüğü değil, senin ne hissettiğin önemlidir.",
  "Korkuların üzerine git, onlar senin en büyük öğretmenlerindir.",
  "Başarı bir varış noktası değil, bir yaşam tarzıdır.",
  "Kendi gücünü keşfet, dünyayı değiştirebilirsin.",
  "Zor zamanlar geçer, ama güçlü insanlar kalır.",
  "Her sabah yeni bir şansla uyanırsın, onu iyi değerlendir.",
  "Disiplin, hedeflerinle başarı arasındaki köprüdür.",
  "Sadece harekete geçenler dünyayı değiştirebilir.",
  "İnanınç, imkansızı mümkün kılar.",
  "Başarısızlık bir son değil, yeniden başlamak için bir derstir.",
  "Hayallerine giden yol, cesaretinden geçer.",
  "Kendine bir söz ver ve onu asla tutmamayı düşünme.",
  "Sabır, başarının en sadık dostudur.",
  "Büyük hırslar, büyük başarılar getirir.",
  "Bugün ne yaparsan, yarın o olursun.",
  "Düşüncelerin senin kaderindir, onları güzelleştir.",
  "Hayat bir aynadır, ona gülümsersen o da sana gülümser.",
  "Zirve yalnızdır ama manzarası harikadır.",
  "Asla durma, yavaş gitmekten korkma ama yerinde saymaktan kork.",
  "Işığını karartanlara inat, daha parlak yan.",
  "Kendine meydan oku, sınırlarını sen çiz.",
  "Başarı, sessizce çalışıp gürültüyle sonuç almaktır.",
  "Her engel, aslında gizli bir fırsattır.",
  "Mutluluk bir seçimdir, başarı ise o seçimin sonucudur.",
  "Yolun ne kadar uzun olduğu değil, nasıl yürüdüğün önemlidir.",
  "Kendini sevmeye başladığında, her şey değişir.",
  "Cesur ol, hayat risk alanları sever.",
  "Bitene kadar her şey imkansız görünür.",
  "Bugün bir tohum ek, yarın orman olur.",
  "Zihnini eğit, bedenin onu takip edecektir.",
  "En büyük risk, hiçbir risk almamaktır.",
  "İmkansız kelimesi sadece sözlüklerde bulunur.",
  "Başarmak için önce inanmak gerekir.",
  "Hayatın dizginlerini eline al ve sür.",
  "Fırsatlar kapını çalmıyorsa, bir kapı inşa et.",
  "Geçmişini unut, geleceğine odaklan.",
  "Her gün bir iyilik yap, ruhun beslensin.",
  "Daha iyisini yapana kadar en iyisi sen ol.",
  "Yıldızlara ulaşmak istiyorsan, ayaklarını yerden kesmelisin.",
  "Pes etmek, kaybetmeyi kabul etmektir.",
  "Hedefin ay olsun, ıskalarsan yıldızlara düşersin.",
  "Çalışmak, şansın en büyük rakibidir.",
  "Kendi yolunu bulamıyorsan, bir yol aç.",
  "Zayıflıklarını güce dönüştür.",
  "Her hata, bir tecrübedir.",
  "Büyük düşün, küçükten başla.",
  "Enerjini hayallerine harca, endişelerine değil.",
  "Kendine güvenen bir insan, binlerce orduya bedeldir.",
  "Başarı, yoldan sapmadan devam edebilmektir.",
  "İlham bekleme, onu sen yarat.",
  "Hayat bir macera, onu cesurca yaşa.",
  "Asla 'belki' deme, 'yapacağım' de.",
  "Odaklandığın her şey büyür.",
  "Kendini geliştirmek için her günü bir fırsat gör.",
  "Karanlık olmadan ışık fark edilmez.",
  "Zorluklar, ruhun antrenmanıdır.",
  "Hayallerin fısıltıyla başlar, çığlıkla biter.",
  "Başarılı olmanın sırrı, başlamaktır.",
  "Her fırtınadan sonra gökkuşağı çıkar.",
  "Kendi kahramanın ol.",
  "Sıradanlığı kabul etme, her zaman fazlasını iste.",
  "Zaman akar, sen de onunla birlikte yüksel.",
  "İçindeki ateşi asla söndürme.",
  "Başarı, sabrın meyvesidir.",
  "Hayat seni zorladığında, daha güçlü it.",
  "Küçük detaylar, büyük resmin parçalarıdır.",
  "Kendine inanmak, başarmanın yarısıdır.",
  "Engelleri birer basamak olarak kullan.",
  "Gelecek, hayallerine inananlara aittir.",
  "Daha hızlı koşmak için bazen yavaşlamak gerekir.",
  "Zihnini serbest bırak, başarıyı yakala.",
  "Hayat bir hediye, onu en iyi şekilde aç.",
  "Kendini keşfettiğinde, sınırların kaybolur.",
  "Her gün yeni bir destan yazabilirsin.",
  "Başarı, konfor alanından çıktığında başlar.",
  "Azimle çalışan, dağı deler.",
  "Umut, her zaman bir yol bulur.",
  "Korku, başarının önündeki en büyük engeldir; onu yık.",
  "İlerlemek için arkana bakma.",
  "Dünya senin sahnen, en iyi rolünü oyna.",
  "Fikirlerini eyleme dönüştür.",
  "Başkalarının hayalleriyle yaşama, kendi hayallerini gerçekleştir.",
  "Hayatın ritmine ayak uydur.",
  "Her şey senin elinde, bunu asla unutma.",
  "Başarı, düştüğünde kalkabilme sanatıdır.",
  "Zihnin güçlüyse, bedenin her şeyi yapar.",
  "Gülümse, çünkü direnmenin en güzel yoludur.",
  "En iyi yatırım, kendine yaptığın yatırımdır.",
  "Sen başla, yol kendini gösterecektir.",
  "Her nefes, yeni bir umut için bir fırsattır.",
  "Güneşin doğuşuna odaklan, geceyi geride bırak.",
  "Kendi sınırlarını zorlamak, özgürlüğün anahtarıdır.",
  "Zihin neyi hayal ederse, el onu inşa eder.",
  "Başkalarından değil, kendinden daha iyi olmaya odaklan.",
  "Cesaret, korkusuzluk değil, korkuya rağmen devam etmektir.",
  "En büyük projen, kendi karakterindir.",
  "Küçük kazanımlar, büyük zaferlerin habercisidir.",
  "Hayat, senin ona verdiğin anlam kadardır.",
  "Zorluklar, elmastan daha değerli tecrübeler barındırır.",
  "Her gün bir iyilik yap, kalbin ferahlasın.",
  "İnandığın yolda yürürken, ayak seslerin dünyaya ilham olsun.",
  "Kendi ışığını paylaştıkça, karanlık azalır.",
  "Başarı, hazırlıklı olanlara fısıldar.",
  "Dünü unutma ama bugünü yaşa ki yarını kurabilesin.",
  "Huzur, içindeki sese kulak verdiğinde başlar.",
  "Büyük idealler, büyük disiplin gerektirir.",
  "Hayallerin, senin ruhunun pusulasıdır.",
  "Asla 'geç kaldım' deme, 'başlıyorum' de.",
  "Sabrın sonu, selametin tam ortasıdır.",
  "Işığını söndürmeye çalışanlara, alevinle cevap ver.",
  "Kendini tanımak, en büyük bilgeliktir.",
  "Her engel, sana yeni bir yetenek kazandırır.",
  "Gülümsemen, dünyadaki en güçlü silahtır.",
  "Hedefine sadık kal, yol seni gitmen gereken yere götürür.",
  "Tutku, sıradan olanı sıra dışı yapandır.",
  "Emeğin sessizdir ama sonuçların gürültülü olsun.",
  "Kendine güven, evren sana yol açacaktır.",
  "Her düşüş, daha yüksek bir sıçrayış için hazırlıktır.",
  "Zamanını güzelliklere harca, nefret seni yorar.",
  "Kalbinin sesini dinle, o seni yanıltmaz.",
  "Küçük bir adım, beklemekten bin kat daha iyidir.",
  "Zirveye değil, attığın her adıma odaklan.",
  "Hayat bir senfoni, sen kendi partini en iyi şekilde çal.",
  "Başkalarının gölgesinde değil, kendi güneşinde parla.",
  "Zorluklar, ruhunun parlamasını sağlayan zımparalardır.",
  "Sen bir mucizesin, bunu asla unutma.",
  "Başlamak için en iyi zaman, şimdidir.",
  "Kararlılık, imkansızın en büyük düşmanıdır.",
  "Içindeki devi uyandır, dünya seni bekliyor.",
  "Hayatın renklerini sen seç, fırça senin elinde.",
  "Korkularını yanına al ama niiden seni yönetmesine izin verme.",
  "Her sabah bir hediye olarak verilir, onu iyi aç.",
  "Senin enerjin, senin imzan gibidir.",
  "Büyük değişimler, küçük kararlarla başlar.",
  "Hatalarından ders al, onlar senin basamaklarındır.",
  "Potansiyelin, okyanus kadar derindir.",
  "Kendini olduğun gibi sev, gelişim doğal olarak gelecektir.",
  "Dürüstlük ve azim, seni her zaman en doğru yere ulaştırır.",
  "Yolun sonunda değil, yolun her anında başarıyı bul.",
  "Sen başla, yol kendini gösterecektir."
];

let availableIndices = [];
let lastIndex = -1;

/**
 * Returns a random motivational quote, ensuring no repeats until all are seen
 */
export function getRandomQuote() {
  if (availableIndices.length === 0) {
    // Fill the pool with all indices and shuffle
    availableIndices = Array.from({ length: quotes.length }, (_, i) => i);
    // Fisher-Yates shuffle
    for (let i = availableIndices.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [availableIndices[i], availableIndices[j]] = [availableIndices[j], availableIndices[i]];
    }

    // Safety check: avoid repeating the last quote as the first of the new cycle
    if (availableIndices.length > 1 && availableIndices[availableIndices.length - 1] === lastIndex) {
      const swapIdx = Math.floor(Math.random() * (availableIndices.length - 1));
      [availableIndices[availableIndices.length - 1], availableIndices[swapIdx]] =
        [availableIndices[swapIdx], availableIndices[availableIndices.length - 1]];
    }
  }

  const index = availableIndices.pop();
  lastIndex = index;
  return quotes[index];
}

export default quotes;
